gha/validate-check: don't run post-merge
I noticed that this workflow was running both before, and after merging a
pull request. When running after it's merged, it gets confused and the check
will be failing (post merge);

    Modified files: .github/workflows/.dco.yml, .github/workflows/.test-unit.yml, .github/workflows/.test.yml, .github/workflows/.vm.yml, .github/workflows/.windows.yml, .github/workflows/buildkit.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/test.yml, .github/workflows/validate-pr.yml
    Touches version: false
    Base ref: master
    Error: PR must have a milestone set (expected: 29.7.0)

Add an extra condition so that the check is only triggered while the PR
is open, not after it's closed or merged. Also add `reopened` as event,
to make sure it's run if someone would close/reopen the PR.

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>