integration/build: make TestBuildEmitsImageCreateEvent less noisy
This test by default was outputing the build-progress output, and printing
a log for every event received, which made the test output rather noisy;

    === RUN   TestBuildEmitsImageCreateEvent
    === RUN   TestBuildEmitsImageCreateEvent/v1
        build_test.go:765: {"stream":"Step 1/2 : FROM busybox"}

            {"stream":"\n"}

            {"stream":" ---\u003e 19d689bc58fd\n"}

            {"stream":"Step 2/2 : RUN echo hello \u003e /hello"}

            {"stream":"\n"}

            {"stream":" ---\u003e Running in 538c10d10d69\n"}

            {"stream":" ---\u003e ca6d3b3e2dea\n"}

            {"aux":{"ID":"sha256:ca6d3b3e2dea645eeddd838da65fd06986da1392b6091dd3d3b89f239dc44f57"}}

            {"stream":"Successfully built ca6d3b3e2dea\n"}

        build_test.go:776: Got event type: container action: create
        build_test.go:776: Got event type: container action: attach
        build_test.go:776: Got event type: network action: connect
        build_test.go:776: Got event type: container action: start
        build_test.go:776: Got event type: network action: disconnect
        build_test.go:776: Got event type: container action: die
        build_test.go:776: Got event type: image action: create
    === RUN   TestBuildEmitsImageCreateEvent/v2
        build_test.go:765: {"id":"moby.buildkit.trace","aux":"Cm8KR3NoYTI1NjowZWViNmZmNTg0ZDJhODEwODhjMTJlNmVkODMxZDcyNWVhMjZmNTg2NjcyNDQ0MzU3NTNkNmZiOGVhMDBiNGFiGiRbaW50ZXJuYWxdIGxvYWQgcmVtb3RlIGJ1aWxkIGNvbnRleHQ="}

            {"id":"moby.buildkit.trace","aux":"CnwKR3NoYTI1NjowZWViNmZmNTg0ZDJhODEwODhjMTJlNmVkODMxZDcyNWVhMjZmNTg2NjcyNDQ0MzU3NTNkNmZiOGVhMDBiNGFiGiRbaW50ZXJuYWxdIGxvYWQgcmVtb3RlIGJ1aWxkIGNvbnRleHQqCwj+tIC7BhCxkpNl"}

            {"id":"moby.buildkit.trace","aux":"CokBCkdzaGEyNTY6MGVlYjZmZjU4NGQyYTgxMDg4YzEyZTZlZDgzMWQ3MjVlYTI2ZjU4NjY3MjQ0NDM1NzUzZDZmYjhlYTAwYjRhYhokW2ludGVybmFsXSBsb2FkIHJlbW90ZSBidWlsZCBjb250ZXh0KgsI/rSAuwYQsZKTZTILCP60gLsGELmTrHg="}

            {"id":"moby.buildkit.trace","aux":"CokBCkdzaGEyNTY6MGVlYjZmZjU4NGQyYTgxMDg4YzEyZTZlZDgzMWQ3MjVlYTI2ZjU4NjY3MjQ0NDM1NzUzZDZmYjhlYTAwYjRhYhokW2ludGVybmFsXSBsb2FkIHJlbW90ZSBidWlsZCBjb250ZXh0KgsI/rSAuwYQpZC3eDILCP60gLsGELbLuXg="}

            {"id":"moby.buildkit.trace","aux":"CqMBCkdzaGEyNTY6MzFjMGEyZDk1N2Q2MTQ2ZjE0NDEyNTM4YTc2YTAxNjhlOWQ5NzY2ZjA0ZjNmMDM4OGQ1YzdjNjQ1ODQ0NDQ3YxJHc2hhMjU2OjBlZWI2ZmY1ODRkMmE4MTA4OGMxMmU2ZWQ4MzFkNzI1ZWEyNmY1ODY2NzI0NDQzNTc1M2Q2ZmI4ZWEwMGI0YWIaD2NvcHkgL2NvbnRleHQgLw=="}

            {"id":"moby.buildkit.trace","aux":"CrABCkdzaGEyNTY6MzFjMGEyZDk1N2Q2MTQ2ZjE0NDEyNTM4YTc2YTAxNjhlOWQ5NzY2ZjA0ZjNmMDM4OGQ1YzdjNjQ1ODQ0NDQ3YxJHc2hhMjU2OjBlZWI2ZmY1ODRkMmE4MTA4OGMxMmU2ZWQ4MzFkNzI1ZWEyNmY1ODY2NzI0NDQzNTc1M2Q2ZmI4ZWEwMGI0YWIaD2NvcHkgL2NvbnRleHQgLyoLCP60gLsGEIyYn3s="}

            {"id":"moby.buildkit.trace","aux":"Cr4BCkdzaGEyNTY6MzFjMGEyZDk1N2Q2MTQ2ZjE0NDEyNTM4YTc2YTAxNjhlOWQ5NzY2ZjA0ZjNmMDM4OGQ1YzdjNjQ1ODQ0NDQ3YxJHc2hhMjU2OjBlZWI2ZmY1ODRkMmE4MTA4OGMxMmU2ZWQ4MzFkNzI1ZWEyNmY1ODY2NzI0NDQzNTc1M2Q2ZmI4ZWEwMGI0YWIaD2NvcHkgL2NvbnRleHQgLyoLCP60gLsGEIyYn3syDAj+tIC7BhCrvMGHAQ=="}

            {"id":"moby.buildkit.trace","aux":"CpYBCkdzaGEyNTY6OTQxZDA2ZjIwMTljOWJmN2FjM2MyZjc5MThhNDQ3ZTU5ZmRkNTEwM2IzMDg0NGRhZmQ5OGFlODE3NjRjYzk4ZBo9W2ludGVybmFsXSBsb2FkIG1ldGFkYXRhIGZvciBkb2NrZXIuaW8vbGlicmFyeS9idXN5Ym94OmxhdGVzdCoMCP60gLsGEPzY+IgB"}

            {"id":"moby.buildkit.trace","aux":"CqQBCkdzaGEyNTY6OTQxZDA2ZjIwMTljOWJmN2FjM2MyZjc5MThhNDQ3ZTU5ZmRkNTEwM2IzMDg0NGRhZmQ5OGFlODE3NjRjYzk4ZBo9W2ludGVybmFsXSBsb2FkIG1ldGFkYXRhIGZvciBkb2NrZXIuaW8vbGlicmFyeS9idXN5Ym94OmxhdGVzdCoMCP60gLsGEPzY+IgBMgwI/rSAuwYQk9mDiQE="}

            {"id":"moby.buildkit.trace","aux":"CrEBCkdzaGEyNTY6ZTNmZGU0ZDc3MmYxZjUyMGVlMzllNzA3YTcyNGNhNjRiN2VhM2IyMGYwOTc2ZDJmN2NiNDBkY2Q5MWU2NTk1YRJHc2hhMjU2OjIyNzAwYzkxMGNmY2I3MjNjZGYyZmNjMGYxNzQ1MjAzMDQxNzk1NmY0ZDhiZjEzZjZkZmRkZWM3NjgxZDcxODAaHVsyLzJdIFJVTiBlY2hvIGhlbGxvID4gL2hlbGxvCnYKR3NoYTI1NjoyMjcwMGM5MTBjZmNiNzIzY2RmMmZjYzBmMTc0NTIwMzA0MTc5NTZmNGQ4YmYxM2Y2ZGZkZGVjNzY4MWQ3MTgwGitbMS8yXSBGUk9NIGRvY2tlci5pby9saWJyYXJ5L2J1c3lib3g6bGF0ZXN0"}

            {"id":"moby.buildkit.trace","aux":"CoQBCkdzaGEyNTY6MjI3MDBjOTEwY2ZjYjcyM2NkZjJmY2MwZjE3NDUyMDMwNDE3OTU2ZjRkOGJmMTNmNmRmZGRlYzc2ODFkNzE4MBorWzEvMl0gRlJPTSBkb2NrZXIuaW8vbGlicmFyeS9idXN5Ym94OmxhdGVzdCoMCP60gLsGEKKYuYkB"}

            {"id":"moby.buildkit.trace","aux":"CpIBCkdzaGEyNTY6MjI3MDBjOTEwY2ZjYjcyM2NkZjJmY2MwZjE3NDUyMDMwNDE3OTU2ZjRkOGJmMTNmNmRmZGRlYzc2ODFkNzE4MBorWzEvMl0gRlJPTSBkb2NrZXIuaW8vbGlicmFyeS9idXN5Ym94OmxhdGVzdCoMCP60gLsGEKKYuYkBMgwI/rSAuwYQhurIiQE="}

            {"id":"moby.buildkit.trace","aux":"CoQBCkdzaGEyNTY6MjI3MDBjOTEwY2ZjYjcyM2NkZjJmY2MwZjE3NDUyMDMwNDE3OTU2ZjRkOGJmMTNmNmRmZGRlYzc2ODFkNzE4MBorWzEvMl0gRlJPTSBkb2NrZXIuaW8vbGlicmFyeS9idXN5Ym94OmxhdGVzdCoMCP60gLsGEPGI0YkB"}

            {"id":"moby.buildkit.trace","aux":"CpIBCkdzaGEyNTY6MjI3MDBjOTEwY2ZjYjcyM2NkZjJmY2MwZjE3NDUyMDMwNDE3OTU2ZjRkOGJmMTNmNmRmZGRlYzc2ODFkNzE4MBorWzEvMl0gRlJPTSBkb2NrZXIuaW8vbGlicmFyeS9idXN5Ym94OmxhdGVzdCoMCP60gLsGEPGI0YkBMgwI/rSAuwYQv9CgkAE="}

            {"id":"moby.buildkit.trace","aux":"Cr8BCkdzaGEyNTY6ZTNmZGU0ZDc3MmYxZjUyMGVlMzllNzA3YTcyNGNhNjRiN2VhM2IyMGYwOTc2ZDJmN2NiNDBkY2Q5MWU2NTk1YRJHc2hhMjU2OjIyNzAwYzkxMGNmY2I3MjNjZGYyZmNjMGYxNzQ1MjAzMDQxNzk1NmY0ZDhiZjEzZjZkZmRkZWM3NjgxZDcxODAaHVsyLzJdIFJVTiBlY2hvIGhlbGxvID4gL2hlbGxvKgwI/rSAuwYQwvqtkgE="}

            {"id":"moby.buildkit.trace","aux":"Cs0BCkdzaGEyNTY6ZTNmZGU0ZDc3MmYxZjUyMGVlMzllNzA3YTcyNGNhNjRiN2VhM2IyMGYwOTc2ZDJmN2NiNDBkY2Q5MWU2NTk1YRJHc2hhMjU2OjIyNzAwYzkxMGNmY2I3MjNjZGYyZmNjMGYxNzQ1MjAzMDQxNzk1NmY0ZDhiZjEzZjZkZmRkZWM3NjgxZDcxODAaHVsyLzJdIFJVTiBlY2hvIGhlbGxvID4gL2hlbGxvKgwI/rSAuwYQwvqtkgEyDAj+tIC7BhDshP7sAQ=="}

            {"id":"moby.buildkit.trace","aux":"CmsKR3NoYTI1NjpmMWM5ZDIzNTNhOWRlZjgwOTI2OGRmMjhhMjU4YzExNTA2ODcxMWE0ZmFiYzM1MjNkOGJhZDIxOTgyMDc3MjFjGhJleHBvcnRpbmcgdG8gaW1hZ2UqDAj+tIC7BhC6trLuARJ3ChBleHBvcnRpbmcgbGF5ZXJzEkdzaGEyNTY6ZjFjOWQyMzUzYTlkZWY4MDkyNjhkZjI4YTI1OGMxMTUwNjg3MTFhNGZhYmMzNTIzZDhiYWQyMTk4MjA3NzIxYzIMCP60gLsGEIe6s+4BOgwI/rSAuwYQq7az7gE="}

            {"id":"moby.buildkit.trace","aux":"EoUBChBleHBvcnRpbmcgbGF5ZXJzEkdzaGEyNTY6ZjFjOWQyMzUzYTlkZWY4MDkyNjhkZjI4YTI1OGMxMTUwNjg3MTFhNGZhYmMzNTIzZDhiYWQyMTk4MjA3NzIxYzIMCP60gLsGEOz5ovsBOgwI/rSAuwYQq7az7gFCDAj+tIC7BhDV8qL7AQ=="}

            {"id":"moby.buildkit.trace","aux":"ErwBClV3cml0aW5nIGltYWdlIHNoYTI1Njo5YjIzODY3ODkzZGMyZDVlM2UxNDBhYjBlY2Y1ZGI4MzlhYjA0YzQ0NjRiNjMyZTQ5ZTg3YzBmOThkZDEyYzFhEkdzaGEyNTY6ZjFjOWQyMzUzYTlkZWY4MDkyNjhkZjI4YTI1OGMxMTUwNjg3MTFhNGZhYmMzNTIzZDhiYWQyMTk4MjA3NzIxYzIMCP60gLsGEPHIq/sBOgwI/rSAuwYQ38Wr+wE="}

            {"id":"moby.buildkit.trace","aux":"EsoBClV3cml0aW5nIGltYWdlIHNoYTI1Njo5YjIzODY3ODkzZGMyZDVlM2UxNDBhYjBlY2Y1ZGI4MzlhYjA0YzQ0NjRiNjMyZTQ5ZTg3YzBmOThkZDEyYzFhEkdzaGEyNTY6ZjFjOWQyMzUzYTlkZWY4MDkyNjhkZjI4YTI1OGMxMTUwNjg3MTFhNGZhYmMzNTIzZDhiYWQyMTk4MjA3NzIxYzIMCP60gLsGEOuB7vwBOgwI/rSAuwYQ38Wr+wFCDAj+tIC7BhCT/+38AQ=="}

            {"id":"moby.buildkit.trace","aux":"CnkKR3NoYTI1NjpmMWM5ZDIzNTNhOWRlZjgwOTI2OGRmMjhhMjU4YzExNTA2ODcxMWE0ZmFiYzM1MjNkOGJhZDIxOTgyMDc3MjFjGhJleHBvcnRpbmcgdG8gaW1hZ2UqDAj+tIC7BhC6trLuATIMCP60gLsGEJG6x4QC"}

            {"id":"moby.image.id","aux":{"ID":"sha256:9b23867893dc2d5e3e140ab0ecf5db839ab04c4464b632e49e87c0f98dd12c1a"}}

        build_test.go:776: Got event type: image action: create

This patch preserves both, but only prints them if the test failed to
help debugging failures.

With this patch:

On success:

    === RUN   TestBuildEmitsImageCreateEvent
    === RUN   TestBuildEmitsImageCreateEvent/v1
    === RUN   TestBuildEmitsImageCreateEvent/v2
    --- PASS: TestBuildEmitsImageCreateEvent (1.53s)
        --- PASS: TestBuildEmitsImageCreateEvent/v1 (0.48s)
        --- PASS: TestBuildEmitsImageCreateEvent/v2 (1.03s)
    PASS

When failing:

    === Failed
    === FAIL: arm64.integration.build TestBuildEmitsImageCreateEvent/v1 (0.97s)
        build_test.go:789: assertion failed: 1 (int) != 0 (imageCreateEvts int)
        build_test.go:790: build-logs:
            {"stream":"Step 1/2 : FROM busybox"}
            {"stream":"\n"}
            {"stream":" ---\u003e 19d689bc58fd\n"}
            {"stream":"Step 2/2 : RUN echo hello \u003e /hello"}
            {"stream":"\n"}
            {"stream":" ---\u003e Running in 119e771bcb1a\n"}
            {"stream":" ---\u003e 289982143d91\n"}
            {"aux":{"ID":"sha256:289982143d912b1c11d95dddfb59640c175fb29a9a00f0223a1ad18972b6df74"}}
            {"stream":"Successfully built 289982143d91\n"}

        build_test.go:791: events received:
            type: container, action: create
            type: container, action: attach
            type: network, action: connect
            type: container, action: start
            type: network, action: disconnect
            type: container, action: die
            type: image, action: create
        --- FAIL: TestBuildEmitsImageCreateEvent/v1 (0.97s)

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>