multierror: make it consistent when there's a single error
If a single error is passed to `multierror.Join`, `joinError.Error()`
returns the error as is. However, due to the multiline formatting
applied otherwise, it's better to add a line break between the preamble
and the multierror string when wrapping it, eg.:

```golang
fmt.Errorf("invalid network config:\n%w", multierror.Join(errs...))
```

This commit removes this special case to make the format consistent no
matter how many errors are joined:

```
invalid network config:
some error

invalid network config:
* some error
```

Signed-off-by: Albin Kerouanton <albinker@gmail.com>