integration-cli: fix TestInspectContainerFilterInt
This test was failing with current versions of the CLI, which don't print
the container-ID;

    === FAIL: amd64.integration-cli TestDockerCLIInspectSuite/TestInspectContainerFilterInt (0.23s)
    docker_cli_inspect_test.go:166: assertion failed: error is not nil: failed to inspect :
    invalid container name or ID: value is empty

        --- FAIL: TestDockerCLIInspectSuite/TestInspectContainerFilterInt (0.23s)

    === FAIL: amd64.integration-cli TestDockerCLIInspectSuite (4.78s)

This looks like a legit regression or change in behavior (may have been
intentional because of the `-a` / `--attach`). Testing with different
versions; change in behavior was in 28.0

    docker run -qit --rm -v /var/run/docker.sock.raw:/var/run/docker.sock docker:25-cli sh -c 'echo "blahblah" | docker run -i -a stdin busybox cat'
    b6c9edfdd5b94a0173fc06c7d9f3eabaa08a2b1aee9007a7ada2fa312f2df0a9

    docker run -qit --rm -v /var/run/docker.sock.raw:/var/run/docker.sock docker:26-cli sh -c 'echo "blahblah" | docker run -i -a stdin busybox cat'
    fc78ba645dd23cbaa7353e221476193b9fb14b1098571ec9614c4fba09866332

    docker run -qit --rm -v /var/run/docker.sock.raw:/var/run/docker.sock docker:27-cli sh -c 'echo "blahblah" | docker run -i -a stdin busybox cat'
    e59843ebe664ea016f257ea256239e617c2a39a5d3c8eb046ddfb3217d6fad25

    docker run -qit --rm -v /var/run/docker.sock.raw:/var/run/docker.sock docker:28-cli sh -c 'echo "blahblah" | docker run -i -a stdin busybox cat'
    # no output

It's not related to the test itself, so we can just use a fixed name for
the container; the test can also be simplified, because `cat` and piping
input is not related either, but keeping both for now as a reminder that
it needs to be looked into.

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>