Fix integration plugin tests wrt Go 1.12
For some reason still mysterious to me, Go 1.12 beta1 doesn't
like the environment in which we run `go build` to build dummy
plugins for tests, giving an error message like this one:

> 00:13:28.931 helpers_test.go:36: error building basic plugin bin: build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined

It's a bit misleading since setting $HOME, or $XDG_CACHE_HOME, or
$GOCACHE env var is not helping to fix the error. What happens is
to remove the `CGO_ENABLED=0` variable, replacing it with the
`-tags netgo` which should result in the same binary.

[v2: also patch internal/test/fixtures/plugin/plugin.go]

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>