gha: downgrade rootless back to 22.04
Looks like rootless doesn't like running on 24.04;

    ---> Making bundle: .integration-daemon-start (in bundles/test-integration)
    Using test binary /usr/local/cli-integration/docker
    # DOCKER_EXPERIMENTAL is set: starting daemon with experimental features enabled!
    Not: starting.
    Starting dockerd
    INFO: Waiting for daemon to start...
    ...........................................................
    error: daemon at unix:///go/src/github.com/docker/docker/bundles/test-integration/docker.sock fails to '/usr/local/cli-integration/docker version':
    Client:
     Version:      17.06.2-ce
     API version:  1.30
     Go version:   go1.8.3
     Git commit:   cec0b72
     Built:        Tue Sep  5 19:57:21 2017
     OS/Arch:      linux/amd64
    Cannot connect to the Docker daemon at unix:///go/src/github.com/docker/docker/bundles/test-integration/docker.sock. Is the docker daemon running?
    make: *** [Makefile:231: test-integration] Error 1
    Error: Process completed with exit code 2.

logs:

    + [ -w /tmp/docker-1000 ]
    + [ -d /home/unprivilegeduser ]
    + rootlesskit=
    + command -v docker-rootlesskit
    + command -v rootlesskit
    + rootlesskit=rootlesskit
    + break
    + [ -z rootlesskit ]
    + : /tmp/docker-1000/dockerd-rootless
    + :
    + :
    + : builtin
    + : auto
    + : auto
    + :
    + net=
    + mtu=
    + [ -z  ]
    + command -v slirp4netns
    + [ -z  ]
    + command -v vpnkit
    + net=vpnkit
    + [ -z  ]
    + mtu=1500
    + host_loopback=--disable-host-loopback
    + [  = false ]
    + dockerd=dockerd
    + [ -z  ]
    + _DOCKERD_ROOTLESS_CHILD=1
    + export _DOCKERD_ROOTLESS_CHILD
    + id -u
    + [ 1000 = 0 ]
    + command -v selinuxenabled
    + exec rootlesskit --state-dir=/tmp/docker-1000/dockerd-rootless --net=vpnkit --mtu=1500 --slirp4netns-sandbox=auto --slirp4netns-seccomp=auto --disable-host-loopback --port-driver=builtin --copy-up=/etc --copy-up=/run --propagation=rslave /usr/local/bin/dockerd-rootless.sh --debug --host unix:///go/src/github.com/docker/docker/bundles/test-integration/docker.sock --storage-driver overlay2 --pidfile bundles/test-integration/docker.pid --userland-proxy=true --experimental
    [rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: operation not permitted

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>