fix TestLoadBalancerSandboxHasNoResolver
This test was added in 38eca8b1e3a017c0748a55d152b1c07542b3fd1c, which
was merged while 7f065ad76f192e57d553f7c33467f843d153b5c3 removed the
config.OptionDataDir option, causing a compile failure;

```
=== Failed
=== FAIL: daemon/libnetwork  (0.00s)
FAIL	github.com/moby/moby/v2/daemon/libnetwork [build failed]

=== Errors
daemon/libnetwork/service_linux_test.go:178:38: undefined: config.OptionDataDir
```

updates 38eca8b1e3a017c0748a55d152b1c07542b3fd1c
updates 7f065ad76f192e57d553f7c33467f843d153b5c3

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>