vendor: bump buildkit to v0.12-m.3
Upgrading the containerd client has the side effect that reproducible
image builds don't reproduce bit-identical images to buildkits with
older versions of the containerd client.

    === FAIL: frontend/dockerfile TestIntegration/TestReproSourceDateEpoch/worker=dockerd-containerd/frontend=client (10.10s)
        dockerfile_test.go:6673: SOURCE_DATE_EPOCH=1673354096
        dockerfile_test.go:6733: OCI archive digest="sha256:5b1465b6d963a464db4c33a499eb913115289ff32c86ab3c81fd62bdeb2ded92"
        dockerfile_test.go:6734: The digest may change depending on the BuildKit version, the snapshotter configuration, etc.
        dockerfile_test.go:6735:
            	Error Trace:	/src/frontend/dockerfile/dockerfile_test.go:6735
            	            				/src/util/testutil/integration/run.go:90
            	            				/src/util/testutil/integration/run.go:204
            	Error:      	Not equal:
            	            	expected: "sha256:d286483eccf4d57c313a3f389cdc196e668d914d319c574b15aabdf1963c5eeb"
            	            	actual  : "sha256:5b1465b6d963a464db4c33a499eb913115289ff32c86ab3c81fd62bdeb2ded92"

The expected digests in the github.com/Mirantis/buildkit@v0.12-m.3
integration tests have been updated to pass with containerd v1.7.33. The
updated buildkit module also has fixes to be more agnostic to the
version of the OpenTelemetry SDK.

Signed-off-by: Cory Snider <csnider@mirantis.com>