windows: skip TestJSONFileLoggerWithOpts on sharing violation
This test is ocassionally failing because we run into a Windows
sharing violation:

```
--- FAIL: TestJSONFileLoggerWithOpts (0.07s)
    jsonfilelog_test.go:187: open C:\Users\ContainerAdministrator\AppData\Local\Temp\docker-logger-344571653\container.log.1: The process cannot access the file because it is being used by another process.
```

This patch attempts to skip the test if we encounter this situation.

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>