integration-cli: adjust TestSaveAndLoadRepoFlags
Account for annotations that are added;

```
=== FAIL: amd64.integration-cli TestDockerCLISaveLoadSuite/TestSaveAndLoadRepoFlags (0.81s)
    docker_cli_save_load_test.go:195: assertion failed:
        --- before
        +++ after
          []image.InspectResponse{
          	{
          		... // 13 identical fields
          		RootFS:   {Type: "layers", Layers: {"sha256:1be74353c3d0fd55fb5638a52953e6f1bc441e5b1710921db9ec2aa20"...}},
          		Metadata: {LastTagTime: s"2026-09-28 09:39:27.421393408 +0000 UTC"},
          		Descriptor: &v1.Descriptor{
          			... // 2 identical fields
          			Size:        535,
          			URLs:        nil,
        - 			Annotations: nil,
        + 			Annotations: map[string]string{
        + 				"io.containerd.image.name":          "docker.io/library/foobar-save-load-test:latest",
        + 				"org.opencontainers.image.ref.name": "latest",
        + 			},
          			Data:         nil,
          			Platform:     nil,
          			ArtifactType: "",
          		},
          		Manifests: nil,
          		Identity:  nil,
          	},
          }
        : inspect is not the same after a save / load
    --- FAIL: TestDockerCLISaveLoadSuite/TestSaveAndLoadRepoFlags (0.81s)
```

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>