quota: Make package compile when `cgo` is disabled
If you're writing a plugin that imports the `overlay2` package (like we are doing), and try to compile without CGo, you get this error:
```
# github.com/docker/docker/quota
../.go_workspace/pkg/mod/github.com/docker/docker@v20.10.8+incompatible/quota/testhelpers.go:100:24: undefined: makeBackingFsDev
```
This PR adds the missing function to the "unsupported" implementation.

Signed-off-by: Pete Woods <pete.woods@circleci.com>