ci: module-replace: ignore Dockerfile for api changes
The API Dockerfile should be ok to ignore for this check, as it's
not part of the module;

```
================================================
================================================
api diff:
-ARG GO_VERSION=1.25.7
+ARG GO_VERSION=1.25.8
================================================
Detected changes in ./api directory, checking for replace rule...
null
ERROR: Changes detected in ./api but go.mod is missing a replace rule for github.com/moby/moby/api
Please run ./hack/vendor.sh replace
================================================
```

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
(cherry picked from commit e064824bbfb7b3bf894ecd2b326db5661cab92aa)
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>