Fix timeout issue of some test cases on AArch64
The `TestCreateWithDuplicateNetworkNames` case can't finished in
the default 10s on ARM platforms, so we need to adjust the timeout
value to avoid the below failure message:

> --- FAIL: TestCreateWithDuplicateNetworkNames (21.61s)
> 	daemon.go:283: [d34836e14f32a] waiting for daemon to start
>	daemon.go:315: [d34836e14f32a] daemon started
>	create_test.go:119: timeout hit after 10s: waiting for tasks to enter run state
>	daemon.go:273: [d34836e14f32a] exiting daemon

The same syndrome for other test cases in this PR, so the same fixing.

Signed-off-by: Dennis Chen <dennis.chen@arm.com>