daemon/cluster/convert: tmpfsOptionsToGRPC: ignore unchecked error (errchkjson)
The function describes that errors are OK to ignore, so we can suppress
the linter warning.

    daemon/cluster/convert/container.go:582:18: Error return value of `encoding/json.Marshal` is not checked (errchkjson)
        jsonBytes, _ := json.Marshal(options)
                        ^

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>