daemon/config: error strings should not be capitalized
    daemon/config/config_unix.go:92:21: error-strings: error strings should not be capitalized or end with punctuation or a newline (revive)
            return fmt.Errorf("Default cgroup namespace mode (%v) is invalid. Use \"host\" or \"private\".", cm) // nolint: golint
                              ^

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
(cherry picked from commit 16ced7622b29df51a5bb77a17332d825a414ccd0)
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>