Fix problem of errors and github.com/pkg/errors
When I used docker package in my project (go 1.23), I found that errors.Is  and .As function was move to errors standard library from go 1.13

So I change the code to overcome it

# github.com/docker/docker/client
../../../../go/pkg/mod/github.com/docker/docker@v27.1.2+incompatible/client/errors.go:28:16: undefined: errors.As
../../../../go/pkg/mod/github.com/docker/docker@v27.1.2+incompatible/client/request.go:127:14: undefined: errors.Is
../../../../go/pkg/mod/github.com/docker/docker@v27.1.2+incompatible/client/request.go:129:14: undefined: errors.Is
../../../../go/pkg/mod/github.com/docker/docker@v27.1.2+incompatible/client/request.go:153:13: undefined: errors.Is