gha: windows: skip "Daemon event logs" if starting daemon was skipped
This step would fail if the daemon was never started ("Starting test daemon"),
or failed to start;

    Run Get-WinEvent -ea SilentlyContinue `
    out-file: D:\a\_temp\2b911acb-4e0e-4684-bf63-606f0da5f7c6.ps1:2
    Line |
       2 |  Get-WinEvent -ea SilentlyContinue `
         |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         | Could not find a part of the path 'D:\a\moby\moby\go\src\github.com\docker\docker\bundles\daemon.log'.
    Error: Process completed with exit code 1.

- Update the step to skip if we never attempted to start the daemon
- Make sure the output directory is created: even if we failed to start
  the daemon (and thus tests weren't run), the startup itself could
  potentially contain information that helps debugging the reason for
  the daemon starting.

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>